name: check-commit

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13.x', '1.x' ]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Print Go version
      run: go version
    - name: Clone repository
      uses: actions/checkout@v1
    - name: Build
      run: make build
    - name: Run tests
      run: make test
    - name: Check formatting
      run: test -z $(go fmt ./...)
    - name: Run linter
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint
        make lint

  sonarCloudTrigger:
    name: sonarcloud.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}