name: check-commit

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20.x', '1.x' ]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Print Go version
      run: go version
    - name: Clone repository
      uses: actions/checkout@v1
    - name: Build
      run: make build
    - name: Run tests
      run: make test
    - name: Check formatting
      run: "test -z $(go fmt ./...) 2>/dev/null || (echo 'ERROR: Formatting is not correct. Run go fmt ./...'; exit 1)"
    - name: Run linter
      run: make lint
