name: Update Dependencies

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update dependencies
      run: make update
    - name: Build
      run: make build
    - name: Check for changed dependencies
      run: git diff --exit-code go.*
