name: update-dependencies

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 5 7 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.20.2
    - uses: actions/checkout@v1
    - name: Update dependencies
      run: make update
    - name: Build
      run: make build
    - name: Check for changed dependencies
      run: git diff --exit-code go.*
