name: Update Dependencies

on:
  schedule:
    - cron:  '0/1 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update dependencies
      run: make update
    - name: Build
      run: make build
    - name: Check for changed dependecies
      run: git diff --exit-code go.*
